### ISSUE TITLE
What does "A=" mean in the Makefile?

### ISSUE THREAD

**Issue by lizhi16** [unikraft/unikraft#451]
Hello, we study the Makefile and find that the parameter "A=" in the Makefile is uncommon for us. We studied the "make --help", but didn't find any explanation. 

What is the function of the "A=" in the Makefile? Thanks!

**Comment by nderjung** [comment]
Hi @lizhi16,

`A=` is the path to the application source (aka this repository) when set up correctly.  The command you ran, `make --help` invokes GNU Make's help menu instead of Unikraft.  For Unikraft's help menu, please try `make help` (without the `--`) as this is a unique target within Unikraft.
