### ISSUE TITLE
Implement event API (eventfd)

### ISSUE THREAD

**Issue by nderjung** [unikraft/unikraft#50]
"The event API provides a mechanism to execute a function when a specific event on a file descriptor occurs or after a given time has passed,"[[1]] and is a suite of common POSIX methods.

The event API can be based on the FreeBSD[[2]] which provides a clean set of methods which implements the standard.

[1]: https://linux.die.net/man/3/event
[2]: https://github.com/freebsd/freebsd/blob/master/sys/compat/linux/linux_event.c

1. https://linux.die.net/man/3/event
2. https://github.com/freebsd/freebsd/blob/master/sys/compat/linux/linux_event.c

**Comment by aadhi0319** [comment]
Hello! I would like to make an attempt at tackling this functionality. To get a little more information, would this involve writing a new library or porting over a pre-existing POSIX compliant event library? Further, is the task to implement eventfd or the entire event syscall suite including event_init, event_dispatch, and more?

**Comment by razvand** [comment]
Hi, @aadhi0319

This task would involve creating a new library that provides the eventfd API. Since this library is going to provide implementations for system calls, I would make this a internal library, as part of the Unikraft core; something like `ukevent`.

The goal is to, of course be able to use the event API, so the task would involve the entire event syscall suite. This **may** be split in two separate components: one with the core eventfd implementation and one for the event syscall suite.
