### ISSUE TITLE
lib/nolibc: `helloworld`  on `AArch64` hangs due to `memcmp()`

### ISSUE THREAD

**Issue by mariasfiraiala** [unikraft/unikraft#728]
### Describe the bug

`helloworld` hangs in `pl011_console_init()` due to very dubious reasons: it simply can't pass over a return instruction in `memcmp()`.

This happens with `gcc 9` on Ubuntu 20.04, on my other system (Ubuntu 22.04) with `gcc 11` and on Ubuntu 20.04 with `clang 10` I had no issues. With no optimizations also, the app behaves just fine, with whatever setup.

The commit that introduces the issue looks very innocent, https://github.com/unikraft/unikraft/commit/b6f0c55f5f2f2a649ed7657ede6f4cd313cf2474, that's why I suspect it might be a deeper problem that is manifesting just now.

### Steps to reproduce

Build `helloworld` on `AArch64` with `nolibc`.

### Expected behavior

I expected the app not to loop infinitely in `memcmp()`.

### Which architectures were you using or does this bug affect?

arm64

### Which platforms were you using or does this bug affect?

kvm

**Comment by eduardvintila** [comment]
The problem seems to boil down to `gcc < 10` optimizing the calls to `memcmp()` due to the missing `-ffreestanding` flag, which is passed only for `gcc >= 10` [1]. A discussion by @marcrittinghaus  and @mschlumpp  on the inclusion on this flag can be found here [2].

Particularly, it seems that `gcc 9` optimizes calls to `memcmp()` by providing a builtin function which ends up calling our `bcmp()` implementation from nolibc that calls `memcmp()`, thus ending up in an infinite recursion.

[ 1 ]: https://github.com/unikraft/unikraft/blob/staging/Makefile.uk#L93
[ 2 ]: https://github.com/unikraft/unikraft/discussions/668
